#!/usr/bin/env python3
"""Add PUA codepoints for IVS glyphs and emit ivs-map.json + pdf-ivs.js."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._c_m_a_p import CmapSubtable

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "assets" / "font.ttf"
MAP_PATH = ROOT / "assets" / "ivs-map.json"
JS_PATH = ROOT / "assets" / "pdf-ivs.js"

# BMP Private Use Area start (U+F000 .. U+F8FF)
PUA_START = 0xF000
PUA_END = 0xF8FF


def collect_ivs_mappings(font: TTFont) -> list[tuple[int, int, int]]:
    """Return sorted list of (base, selector, glyphId) for non-default UVS."""
    rows: list[tuple[int, int, int]] = []
    for table in font["cmap"].tables:
        if table.format != 14:
            continue
        # fontTools: uvsDict is {selector: [(base, glyphNameOrNone), ...]}
        for selector, pairs in table.uvsDict.items():
            for base, glyph in pairs:
                if glyph is None:
                    continue  # default UVS → base cmap glyph
                gid = font.getGlyphID(glyph) if isinstance(glyph, str) else int(glyph)
                rows.append((int(base), int(selector), int(gid)))
    rows.sort(key=lambda r: (r[1], r[0]))
    return rows


def ensure_cmap_entry(cmap_table, code: int, glyph_name: str) -> None:
    cmap_table.cmap[code] = glyph_name


def add_pua_to_cmaps(font: TTFont, assignments: list[tuple[int, str]]) -> None:
    """assignments: list of (pua_codepoint, glyph_name)."""
    # Prefer Unicode BMP + full Unicode tables
    targets = []
    for table in font["cmap"].tables:
        if table.format in (4, 12) and table.platformID in (0, 3):
            targets.append(table)
    if not targets:
        # Create a format 12 Unicode table if somehow missing
        t = CmapSubtable.newSubtable(12)
        t.platformID = 3
        t.platEncID = 10
        t.language = 0
        t.cmap = {}
        font["cmap"].tables.append(t)
        targets = [t]

    for code, gname in assignments:
        for table in targets:
            # format 4 is BMP-only; skip if out of range (ours are BMP)
            if table.format == 4 and code > 0xFFFF:
                continue
            ensure_cmap_entry(table, code, gname)


def write_pdf_ivs_js(mapping: dict[str, str]) -> None:
    # mapping keys "8FBB;E0100" -> "F012"
    js = f"""/*! CAFA PDF IVS helpers — generated by scripts/build-ivs-font.py */
(function (root) {{
  'use strict';

  /** @type {{Record<string, string>}} hex "BASE;VS" -> PUA hex */
  var IVS_MAP = {json.dumps(mapping, ensure_ascii=True, separators=(',', ':'))};

  var _ready = true;
  var _loadPromise = null;

  function hexToCodePoint(hex) {{
    return parseInt(String(hex), 16);
  }}

  /**
   * Optional: load/override map from JSON (local or GAS-intercepted fetch).
   * With the embedded map this is usually a no-op success.
   * @param {{string}} [baseUrl] directory containing ivs-map.json
   */
  function loadIvsMap(baseUrl) {{
    if (_loadPromise) return _loadPromise;
    _ready = true;
    if (!baseUrl) {{
      _loadPromise = Promise.resolve(IVS_MAP);
      return _loadPromise;
    }}
    var url = String(baseUrl).replace(/\\/?$/, '/') + 'ivs-map.json';
    _loadPromise = fetch(url)
      .then(function (res) {{
        if (!res.ok) throw new Error('ivs-map.json HTTP ' + res.status);
        return res.json();
      }})
      .then(function (data) {{
        if (data && typeof data === 'object') {{
          Object.keys(data).forEach(function (k) {{ IVS_MAP[k] = data[k]; }});
        }}
        _ready = true;
        return IVS_MAP;
      }})
      .catch(function () {{
        // Embedded map is enough; ignore fetch failures (e.g. missing Drive file).
        _ready = true;
        return IVS_MAP;
      }});
    return _loadPromise;
  }}

  /**
   * Replace IVS sequences (base + variation selector) with a single PUA char
   * that maps to the correct glyph in the patched font.
   */
  function normalizeIvsText(text) {{
    if (text == null || text === '') return '';
    var s = String(text);
    var out = '';
    var i = 0;
    var cps = Array.from(s); // code points (handles surrogates)
    while (i < cps.length) {{
      var base = cps[i].codePointAt(0);
      var next = i + 1 < cps.length ? cps[i + 1].codePointAt(0) : 0;
      var isVs =
        (next >= 0xfe00 && next <= 0xfe0f) ||
        (next >= 0xe0100 && next <= 0xe01ef);
      if (isVs) {{
        var key =
          base.toString(16).toUpperCase() +
          ';' +
          next.toString(16).toUpperCase();
        var puaHex = IVS_MAP[key];
        if (puaHex) {{
          out += String.fromCodePoint(hexToCodePoint(puaHex));
          i += 2;
          continue;
        }}
      }}
      out += cps[i];
      i += 1;
    }}
    return out;
  }}

  /**
   * Split into grapheme-like units for OCR box layout.
   * Prefers Intl.Segmenter; falls back to code points.
   */
  function splitGraphemes(text) {{
    if (text == null || text === '') return [];
    var s = String(text);
    if (typeof Intl !== 'undefined' && Intl.Segmenter) {{
      try {{
        var seg = new Intl.Segmenter('ja', {{ granularity: 'grapheme' }});
        return Array.from(seg.segment(s), function (x) {{ return x.segment; }});
      }} catch (e) {{ /* fall through */ }}
    }}
    return Array.from(s);
  }}

  root.loadIvsMap = loadIvsMap;
  root.normalizeIvsText = normalizeIvsText;
  root.splitGraphemes = splitGraphemes;
  root.CAFA_IVS_MAP = IVS_MAP;
}})(typeof window !== 'undefined' ? window : globalThis);
"""
    JS_PATH.write_text(js, encoding="utf-8")


def clear_existing_pua(font: TTFont) -> int:
    """Remove prior PUA assignments in U+F000–U+F8FF so rebuilds stay idempotent."""
    removed = 0
    for table in font["cmap"].tables:
        if table.format not in (4, 12):
            continue
        for code in list(table.cmap.keys()):
            if PUA_START <= int(code) <= PUA_END:
                del table.cmap[code]
                removed += 1
    return removed


def main() -> int:
    if not FONT_PATH.exists():
        print(f"ERROR: missing {FONT_PATH}", file=sys.stderr)
        return 1

    font = TTFont(FONT_PATH)
    cleared = clear_existing_pua(font)
    if cleared:
        print(f"Cleared {cleared} existing PUA cmap entries")

    rows = collect_ivs_mappings(font)
    if not rows:
        print("ERROR: no non-default IVS mappings found in font", file=sys.stderr)
        return 1

    if PUA_START + len(rows) - 1 > PUA_END:
        print("ERROR: PUA range overflow", file=sys.stderr)
        return 1

    assignments: list[tuple[int, str]] = []
    mapping: dict[str, str] = {}
    for i, (base, selector, gid) in enumerate(rows):
        pua = PUA_START + i
        gname = font.getGlyphName(gid)
        assignments.append((pua, gname))
        key = f"{base:X};{selector:X}"
        mapping[key] = f"{pua:X}"

    add_pua_to_cmaps(font, assignments)
    font.save(FONT_PATH)
    font.close()

    MAP_PATH.write_text(
        json.dumps(mapping, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    write_pdf_ivs_js(mapping)

    # Sanity: 辻 + E0100
    sample_key = "8FBB;E0100"
    print(f"IVS mappings: {len(mapping)}")
    print(f"辻+E0100 → U+{mapping.get(sample_key, 'MISSING')}")
    print(f"Wrote {FONT_PATH}")
    print(f"Wrote {MAP_PATH}")
    print(f"Wrote {JS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
